install.packages("devtools")
install.packages("shinyjs")
install.packages("plotly")
install.packages("dplyr")
install.packages("tidyr")
install.packages("DT")
install.packages("RCurl")
install.packages("ggbeeswarm")
install.packages("plyr")
install.packages("gridExtra")
install.packages("tidyverse")

devtools::install_github("trestletech/shinyStore")
