# coding: utf-8

"""
    ODM Integration API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: default-released
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "integration_curator"
VERSION = "default-released"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

if __name__ == '__main__':
    setup(
        name=NAME,
        version=VERSION,
        description="ODM Integration API",
        author_email="",
        url="",
        keywords=["Swagger", "ODM Integration API"],
        install_requires=REQUIRES,
        packages=find_packages(),
        include_package_data=True,
        long_description="""\
        No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501
        """
    )
