# coding: utf-8

"""
    ODM Integration API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: default-released
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from integration_curator.models.i_metadata import IMetadata  # noqa: F401,E501
from integration_curator.models.relationships import Relationships  # noqa: F401,E501


class MetadataPresentation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'metadata': 'IMetadata',
        'relationships': 'Relationships'
    }

    attribute_map = {
        'metadata': 'metadata',
        'relationships': 'relationships'
    }

    def __init__(self, metadata=None, relationships=None):  # noqa: E501
        """MetadataPresentation - a model defined in Swagger"""  # noqa: E501

        self._metadata = None
        self._relationships = None
        self.discriminator = None

        if metadata is not None:
            self.metadata = metadata
        if relationships is not None:
            self.relationships = relationships

    @property
    def metadata(self):
        """Gets the metadata of this MetadataPresentation.  # noqa: E501


        :return: The metadata of this MetadataPresentation.  # noqa: E501
        :rtype: IMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this MetadataPresentation.


        :param metadata: The metadata of this MetadataPresentation.  # noqa: E501
        :type: IMetadata
        """

        self._metadata = metadata

    @property
    def relationships(self):
        """Gets the relationships of this MetadataPresentation.  # noqa: E501


        :return: The relationships of this MetadataPresentation.  # noqa: E501
        :rtype: Relationships
        """
        return self._relationships

    @relationships.setter
    def relationships(self, relationships):
        """Sets the relationships of this MetadataPresentation.


        :param relationships: The relationships of this MetadataPresentation.  # noqa: E501
        :type: Relationships
        """

        self._relationships = relationships

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For ``print`` and ``pprint``"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetadataPresentation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other